### ISSUE TITLE
Refresh Hologram

### ISSUE THREAD

**Issue by Vouchs** [JitseB/NPCLib#11]
A method to refresh the hologram above NPC's head.

**Comment by JitseB** [comment]
Hi there,

Thanks for opening this issue! I'll look into this request as soon as #10 is closed.

Thank you for your patience.

**Comment by JitseB** [comment]
Thinking of making the hologram library a separate module. It's currently getting a bit messy...

**Comment by Mooselk** [comment]
Any idea when this will be implemented? Right now I'm using a messy work around.

**Comment by JitseB** [comment]
Working prototype on v1.8 R1 (code on master branch).

![text-update-gif](https://user-images.githubusercontent.com/10088886/67709864-210bc500-f9bf-11e9-9e7c-27e370e0b52e.gif)

**Comment by JitseB** [comment]
Finally released the update containing this method!

You may download it here: https://github.com/JitseB/NPCLib/releases/tag/2.3-SNAPSHOT

Happy coding! 💻
