### ISSUE TITLE
Initiation of wrong packet listeners on 1.7.10-1.8 protocol hack

### ISSUE THREAD

**Issue by Lickem1** [JitseB/NPCLib#12]
https://i.imgur.com/shgmS13.png

**Comment by JitseB** [comment]
That's strange. It looks like NPCLib is creating the TinyProtocol instance for the wrong version, which is not something I've seen happen on my test server.

Could you provide me with your version of Spigot, NPCLib and whether you're using BungeeCord?

**Comment by Lickem1** [comment]
Yes I'm using paper spigot 1.7.10 with 1.8 support, latest version of NPCLib, and I'm not running bungeecord

**Comment by JitseB** [comment]
Ah I see, you're using the protocolhack version. Since I no longer have access to that JAR, could you print `Bukkit#getBukkitVersion` for me?

It looks like the Bukkit version name differs from the package name. Which doesn't seem all that strange since it's a modified build of Spigot.

**Comment by Lickem1** [comment]
Im using zspigot https://www.mc-market.org/resources/7198/

**Comment by JitseB** [comment]
I will soon publish a release with a fix for this issue.

**Comment by JitseB** [comment]
Hi there,

If all went well v1.4.1 should solve your issue. If not, please tell me!

https://github.com/JitseB/NPCLib/releases/tag/v1.4.1

Good luck and happy coding :)
