### ISSUE TITLE
HEX colors

### ISSUE THREAD

**Issue by Patrik950** [JitseB/NPCLib#165]
**Describe the bug**
I tried my colorize method (which by this hologram shows only like &1&lTEXT), too like #RGBRGB and doesn't work 

**NPCLib usage option**
NPCLib can be used in multiple ways, please provide [the number](https://github.com/JitseB/NPCLib#usage) corresponding to your usage option.
1

**NPCLib JAR name**
E.g. npclib-plugin-2.0.1-SNAPSHOT.jar
Newest last npclib-plugin-2.12.1-SNAPSHOT

**Server version**
E.g. CraftBukkit version git-Spigot-a1f2566-97b0057 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) (use command `/version`)
Purpur version git-Purpur-1060 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**To Reproduce**
- Used code  'survivalNPC = Plugin.getInstance().getNPCLib().createNPC(Arrays.asList("#20DF81&lSURVIVAL"
				, "§2TEST123"));' < DOESNT WORK FULL >
or 'survivalNPC = Plugin.getInstance().getNPCLib().createNPC(Arrays.asList(Plugin.Colorize("#20DF81&lSURVIVAL")
				, "§2TEST123"));' < WORKED, but it shows only &1&lTEXT >
- Actions in game 'joined and see the hologram'

**Expected behavior**

----

**Screenshots**

---

**Additional context**

-----

**Comment by JitseB** [comment]
You should use the ChatColor enum. Minecraft only recognizes the `§` for colors. NPCLib does not convert ampersands to the paragraph sign.

Closing issue.
