### ISSUE TITLE
Auto Hide Distance Not Working

### ISSUE THREAD

**Issue by EazyFTW** [JitseB/NPCLib#17]
The autohide distance is not working. It defaults to around 12 blocks, even when setting the value. I tried setting it to 500, and it is still the same.

**Comment by JitseB** [comment]
Hi there, thanks for opening this issue!

Right, the autohide distance. I had to build in a safety feature in to NPCLib, as Minecraft automatically destroys/hides entities when players get outside a certain range and I want to track the NPCs in an efficient manner. This value is set by default to 50 blocks (in NPCLib).

There are "entity-tracking" values that can be changed in the spigot.yml file. I haven't had the time to play around with that, but I reckon that if you change the "entity-tracking-range" and "entity-activation-range" in your spigot.yml file, it will change when the NPC disappears. I think you'll need to set these values to the same amount of blocks as you are spawning the NPCs with (autoHideDistance).

**Comment by EazyFTW** [comment]
Ok, i'll give it a try.

**Comment by EazyFTW** [comment]
Didn't work. I'm going to try to use spigot, instead of just paper spigot.

**Comment by EazyFTW** [comment]
It's also more like 12 blocks, not 50.

**Comment by EazyFTW** [comment]
There are a total of 12 blocks on the right. Different ones so you can see the distance. https://i.eazyftw.com/o5h56if

**Comment by EazyFTW** [comment]
It's even smaller on 1.8.8  (tried to change the range in spigot.yml too. It was set default to 50.

5 blocks in 1.8.8.

**Comment by JitseB** [comment]
I've been a bit silly. I wasn't checking the NPC autohide distance correctly. I'll add a release with this fix soon.

**Comment by JitseB** [comment]
Fixes in [release 1.4.2](https://github.com/JitseB/NPCLib/releases/tag/v1.4.2)!
