### ISSUE TITLE
NPC save system

### ISSUE THREAD

**Issue by LaiMacVN** [JitseB/NPCLib#178]
Does this api have its own save system or i need to make the new one?

**Comment by LaiMacVN** [comment]
this is the question i put the wrong tag

**Comment by JitseB** [comment]
The NPCs are accounted for in the NPCManager class (see [NPCManager class](https://github.com/JitseB/NPCLib/blob/master/api/src/main/java/net/jitse/npclib/internal/NPCManager.java)), you may retrieve all NPCs created through NPCLib and the NPCs visible per player.
