### ISSUE TITLE
Nametag Issue

### ISSUE THREAD

**Issue by EazyFTW** [JitseB/NPCLib#18]
https://i.eazyftw.com/9PGikJS

Happens sometimes when loading NPC.

**Comment by JitseB** [comment]
On what version of NPCLib and spigot?

**Comment by EazyFTW** [comment]
v1.3, and 1.13.2 paperspigot.

**Comment by JitseB** [comment]
Closed due to inactivity. If the problem reoccurs, please reopen this issue with the new issue format.
