### ISSUE TITLE
setSkin Method not working

### ISSUE THREAD

**Issue by termxz** [JitseB/NPCLib#26]
Spawning the NPC works fine and everything but the skin is missing for some reason. I already tried with multiple skins, versions, and an added delay for showing the NPC. 

No error messages and NPCLib loads correctly.

NMS Version: v1_8_R3
NPCLib Version: 2.0

`    @EventHandler`
    `public void onJoin(PlayerJoinEvent e) {`

        MineSkinFetcher.fetchSkinFromIdAsync(725954, skin -> {
            NPC npc = npcLib.createNPC(Arrays.asList(ChatColor.WHITE + "test")).
                    setLocation(e.getPlayer().getLocation()).
                    setSkin(skin).
                    create();

            Bukkit.getScheduler().runTask(this, () -> npc.show(e.getPlayer()));
        });

    }

**Comment by EazyFTW** [comment]
I think in v2.0 you have to set it via the texture and values.

**Comment by termxz** [comment]
Example, please?

**Comment by EazyFTW** [comment]
I lied, but here is an exmaple:
https://github.com/JitseB/NPCLib/blob/master/examples/example-3.java

**Comment by termxz** [comment]
I tried that same thing :(

**Comment by JitseB** [comment]
My mistake! I forgot to update the GameProfile after the skin object changed.

Building v2.0.1 right now. Will post the release shortly.

**Comment by JitseB** [comment]
Release v2.0.1: https://github.com/JitseB/NPCLib/releases/tag/2.0.1
