### ISSUE TITLE
Issue when creating NPC

### ISSUE THREAD

**Issue by baewolfy** [JitseB/NPCLib#28]
Version: 2.0.1-SNAPSHOT

First thing I wanted to mention is that I got an error on serverstart:
[ERROR] NPCLib Failed to initiate. Your server's version (v1_13_R2) is not supported

I suspect that the problem may lie here? I don't know why I get this error though since you say your plugin api supports 1.8 - 1.14.4

Server log: https://pastebin.com/2TggBrhU
Code: https://pastebin.com/mmATSWAS

I debugged a little bit and I noticed that npc is still null even after this line:
npc = npcLib.createNPC(Arrays.asList(name));

So my guess is that something is going wrong there.

I hope you can help me with my issue

Regards Bjarne

**Comment by JitseB** [comment]
Hi there! Thanks for opening this issue.

This is not something that should occur with your version of NPCLib. To further trouble-shoot your problem, could you please provide me the following details?

- **Server version** (e.g. CraftBukkit version git-Spigot-a1f2566-97b0057 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)) (you can get this through `/version`)
- **Usage option of NPCLib** (one of three options, as stated in the [README](https://github.com/JitseB/NPCLib#usage))
- **Using the API or the Plugin JAR?**

**Comment by baewolfy** [comment]
- Server version : CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

- Usage: I used Maven to shade it into my plugin. And then just added it to my artifacts 

- I'm using the API

**Comment by JitseB** [comment]
Ah I see. You're shading the wrong artifact. You see, the API artifact doesn't contain the necessary NMS code. To solve your problem, please shade `npclib-plugin` instead of `npclib-api`.
