### ISSUE TITLE
How to set-up?

### ISSUE THREAD

**Issue by LukiGamerDK** [JitseB/NPCLib#30]
How do i setup the plugin??? iam a noob.. i know
i've found the jar file but when i import it and reload my server i dont get a folder called NPCLib

**Comment by JitseB** [comment]
NPCLib isn't meant as a standalone plugin. It's an API for developers.

You can read the [documentation ](https://github.com/JitseB/NPCLib/blob/master/DOCUMENTATION.md)on how to use the library. (After, ofcourse, you've [imported ](https://github.com/JitseB/NPCLib#usage)NPCLib into your project).

**Comment by JitseB** [comment]
Closed due to inactivity. You may reopen this issue any time. You can also contact me on my email (which you can find on my GitHub profile). Thanks!
