### ISSUE TITLE
PCLib Failed to initiate. Your server's version (v1_14_R1) is not supported

### ISSUE THREAD

**Issue by Ryooth** [JitseB/NPCLib#32]
**Describe the bug**
In the spigotmc repository, you say, that it supports 1.14.4, but it doesnt Load

**NPCLib usage option**
3

**NPCLib JAR name**
npclib-api-2.0.1-SNAPSHOT.jar

**Server version**
This server is running CraftBukkit version git-Spigot-798ea6a-44d675a (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by JitseB** [comment]
Hi there, thanks for opening this issue.

Are you shading `npclib-api` or `npclib-plugin` in your pom file? When shading NPCLib it's important to shade the `npclib-plugin` artifact instead of the API, as this will include the necessary NMS classes.

**Comment by Ryooth** [comment]
Hi. thank you, now i shaded the npclib-plugin instead of the api, and it works.

**Comment by JitseB** [comment]
👍
