### ISSUE TITLE
NPE on Server Start

### ISSUE THREAD

**Issue by A248** [JitseB/NPCLib#34]
**Describe the Bug**
Console error on server startup. NPE on ChunkUnloadEvent.

**NPCLib Usage Option**
Lazy way; plugin install.

**NPCLib Jar Name**
npclib-plugin-2.1-SNAPSHOT.jar

**Server version**
Paper 1.8.8:
`CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`

**To Reproduce**
I'm not exactly sure how to reproduce this error. I've been using NPCLib for a few days now without any kind of errors. Also, I know I don't listen to ChunkUnloadEvent.

My plugin hooks into the NPCLib API. However, this error occurred without any calls to NPCLib, besides `lib = new NPCLib(this.main);`

**Expected Behaviour**
No console errors.

**Screenshots**
[Pastebin of the error](https://pastebin.com/15eXSgc2)

**Other info**
ArimSK is the name of my plugin. I don't listen to ChunkUnloadEvent. No calls to the API except initialising it. Happens multiple times as soon as startup finishes.

**Comment by JitseB** [comment]
Might be a race case, where the managers still had an NPC object tracking without a location. Will be solved in an upcoming update.

Thanks!

**Comment by A248** [comment]
@JitseB It definitely was an anomaly. After I restarted the server this didn't happen, despite my not changing any of the code or configuration for any plugins.

**Comment by JitseB** [comment]
Good to hear that!

**Comment by JitseB** [comment]
Closing issue. Anomalies like this will not happen after upcoming release.
