### ISSUE TITLE
NPC IDs Show in Tablist Momentarily

### ISSUE THREAD

**Issue by A248** [JitseB/NPCLib#38]
**Describe the bug**
Upon joining, NPC IDs are temporarily visible in the tablist display. Their IDs are shown as player names.

**NPCLib usage option**
Plugin installation with API usage by my own plugin.

**NPCLib JAR name**
npclib-plugin-2.1-SNAPSHOT.jar (Planning on updating soon)

**Server version**
PaperSpigot 1.8.8 `CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`

**To Reproduce**
1. Create NPC
2. Call NPC#show in PlayerJoinEvent.
3. Press TAB when joining and see IDs in tablist.

**Expected behavior**
No NPC IDs are visible in tablist since they are not normal players.

**Screenshots**
If you need a screenshot of the issue I can provide it. However, it's quite trivial, and wouldn't be very informative.

**Additional context**
I am using my own Skript addon to call NPC#show when a player joins. The effect should be the same, however, whether it is Skript or a normal Java plugin which calls NPC#show.

All other NPCLib features work as expected.

**Comment by JitseB** [comment]
This is expected behaviour. NPCLib sends packets to players as if the NPCs are normal players of which the packets are sent to the player. Therefore, (on most versions at least) I added the [NPC] prefix.
