### ISSUE TITLE
v1_8_R3 is not supported

### ISSUE THREAD

**Issue by Lickem1** [JitseB/NPCLib#39]
https://i.imgur.com/hPoggkV.png

**Comment by Lickem1** [comment]
Also, could it be my spigot or? https://i.imgur.com/94M7JIR.png

**Comment by JitseB** [comment]
Could you please use the provided issue template?

**Comment by Lickem1** [comment]
where?

**Comment by A248** [comment]
@Lickem1 , check your stacktrace. You have a NPE in your plugin. That's probably causing the error.

**Comment by JitseB** [comment]
The provided stacktrace is not related to the library, nor is additional information provided.

Closing issue for now. You may reopen it at any time (given that the issue template is provided).
