### ISSUE TITLE
A question about future development 

### ISSUE THREAD

**Issue by pluttotv** [JitseB/NPCLib#44]
Hey! i saw this epic NPCLib api ur making here guys, tho i see Jitse really active -> credit to all if needed <3

im working on implementing this plugin of yours in one of mine, which will use your lib to create interactive inventory per arena/mini-game join - and all that logic of what inventory to show when and which game its belong to.

till now i handled all throe sign, which i dont like.

i also want to implement on top of ur code packets of entity move. tho i use protocol lib for that.
so my question is -> do you have any plan in the future to add custom random walk in radios of loc? or like watch an entity when it is close to him, stuff like that to make them more alive?
im talking about stuff like:
Entity Look And Relative Move packet or Entity Look packets send to all players who sees him.
so the npc can walk around and watch people like goalpathfinder -> just simpler.

i pretty much wanna use only ur lib to handle all my npc stuff explosively,  as citizen2 is super heavy and its cost effective for what im looking for is not good... im looking to create alot of custom npc which will walk around the city and also handle quests in the further (beside joining a minigame)
at the end:
before i found this lib i thought to do the same as you guys and create customs npc by NMS or make one with pure packets, so im really happy to find this epic lib which is coded simple and powerful.

Thanks, i didn't know if i should open a ticket or just leave a msg in the discussion of this plugin in spigot. but any way -> keep up the good work.

**Comment by JitseB** [comment]
Hi there, thanks for liking NPCLib!

I do have future plans for NPCLib, A few methods I have in mind are:
* `NPC#lookAt(Entity)`: NPC will look and track entity.
* `NPC#lookAt(Location)`: NPC will look at location.
* `NPC#move(Direction)`: Move the NPC in a certain North, East, South, West direction.
* `NPC#teleport(Location)`: Teleport the NPC to a specific location.

The ideas are there, but I'm very busy with my education and as NPCLib is a free resource which I maintain in my free time, NPCLib doesn't get many major updates too often... 🙄 

Thanks again!

(By the way, if anyone feels like responding to this thread, feel free to do so, I'd like to know what other developers would like to see in NPCLib in the future as well).

**Comment by pluttotv** [comment]
yap that pretty much what i thought about as well.

beside that - just to point up that ur examples use .getID and string list to get record of them.
but there is no method to get all npc string id, for cases you want a list of npc to return there location or have a map if id and not npc to indicate an npc.
 like that you could save id and run it agents the npcManager.

for example:
npcManager.getNpc(id) return the npc you need for some stuff.

also is it impotent to remove players from the show list per npc after they dc?
i saw there is a onLogout method that is not used on NPC Class, but does in can be called on NPCBase types npcs.

**Comment by A248** [comment]
@pluttotv you can always create a PR with new features added. That would be much appreciated :)

**Comment by JitseB** [comment]
Closed due to inactivity. Ticket may be reopened any time.
