### ISSUE TITLE
NPCInteractEvent event never get called

### ISSUE THREAD

**Issue by pluttotv** [JitseB/NPCLib#45]
**Describe the bug**
i made a new class called NpcManager which implements Listener and handle all the npc i use with the plugin. as all 3 examples shows - on join event it create a personal npc on a specific location
and on left/right click - it opens an custom inventory of the player data.

**NPCLib usage option**
option 2

**NPCLib JAR name**
npclib-plugin-2.3.1-SNAPSHOT

**Server version**
This server is running Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**To Reproduce**
- Used code  for join event: (all work - npc registered and showed per player)
@EventHandler
    public void onPlayerJoinEvent(PlayerJoinEvent event) {
        Player p = event.getPlayer();
        //ADD a PLAYER SELF LOOK from the location (playerSelfLoc) which is saved while loading the data of the plugin.
        if(playerSelfLoc != null) {
            //SHOW THE NPCPLAYER TO PLAYER
            List<String> textToNpc = new ArrayList<>();
            textToNpc.add(ChatColor.BLUE + " hey " + ChatColor.WHITE + p.getName());
            NPC playerNpc = npcManager.createNPC(textToNpc);
            privatePlayerNPC.put(p.getUniqueId(), playerNpc);
            playerNpc.setLocation(this.playerSelfLoc);
            playerNpc.create();
            playerNpc.show(p);
        }
        ....
        ....
}

- Used code  for interaction event: (NOT working - never get the string on console nor anything else)
 @EventHandler
    public void onNPCInteract(NPCInteractEvent event) {
        System.out.println("ITS A PLAYER INTERACTING WITH NPC!");
        Player player = event.getWhoClicked();
        ....
        ....
        ....
}

**Expected behavior**
expetec behavior is to get the println on the console - but that never happen.

i didn't had the time to go into the source code and find why, but if i find a solution before
i will be sure to update here.

i dont think its an huge problem probably a missing step - tho i saw all 3 examples and its pretty much the same, also i dont get any error and beside the interaction everything else related and happen over that class -> is working as needed.  

Cheers,
plutto.

**Comment by pluttotv** [comment]
also just in case:

private NPCLib npcManager;

public NpcManager(CrystalQuest thePlugin) {
        this.plugin = thePlugin;
        this.npcManager = new NPCLib(plugin);
 .....
......
}

**Comment by JitseB** [comment]
Are you sure you are registering the listener class correctly?

**Comment by pluttotv** [comment]
yes because i use on the same class both event listeners
public NpcManager(CrystalQuest thePlugin) {
        this.plugin = thePlugin;
        this.npcManager = new NPCLib(plugin);
        npcManager.setAutoHideDistance(30);
        plugin.getServer().getPluginManager().registerEvents(this, plugin);
 ......
......
}

forgot to post the register event but it does happen, it has 3 eventHandlers
the joinEvent on login, the interaction of NPCLib and the leaveEvent on dc.
all work beside the NPCInteractEvent .

**Comment by JitseB** [comment]
Can you post your startup-log? I'd like to know if the netty channel duplex is registered correctly.

**Comment by pluttotv** [comment]
[12:45:45 INFO]: Starting minecraft server version 1.14.4
[12:45:45 INFO]: Loading properties
[12:45:45 INFO]: This server is running Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[12:45:55 WARN]: Plugin NPCLibPlugin v2.3.1-SNAPSHOT does not specify an api-version.
[12:46:00 INFO]: [NPCLibPlugin] Loading NPCLibPlugin v2.3.1-SNAPSHOT
[12:46:09 INFO]: [NPCLibPlugin] Enabling NPCLibPlugin v2.3.1-SNAPSHOT*
[12:46:09 INFO]: [NPCLibPlugin] NPCLib classes loaded
[12:46:35 INFO]: NPCLib Attempting to inject into netty
[12:46:35 INFO]: NPCLib Enabled for Minecraft v1_14_R1

any chance it has anything to do with protocollib ?
i saw NPCLib use tinyProtocol - soo there shouldn't be any conflict.

**Comment by pluttotv** [comment]
any updates?

**Comment by JitseB** [comment]
Are you still having the same problem?

If so, can you try to run your plugin on a separate (new) server with _only_ the (on NPCLib depending) plugin?

**Comment by pluttotv** [comment]
it worked, also i located the plugin that break it.
its LibsDisguises
here is there spigotpage:
https://www.spigotmc.org/resources/libs-disguises.32453/
and the github:
https://github.com/libraryaddict/LibsDisguises/
