### ISSUE TITLE
Minecraft 1.15.X compatibility 

### ISSUE THREAD

**Issue by wasmake** [JitseB/NPCLib#49]
Could you add Minecraft 1.15 compatibility? I could do a merge request but I don't really know about NMS D:

**Comment by JitseB** [comment]
(as posted in #51):
I have been very busy with my degree, luckily @MrMicky-FR created a PR (#52) and added the necessary code for 1.15.

I'll soon be posting a compiled JAR file on both the repo and SpigotMC.

Sorry for the long wait!
