### ISSUE TITLE
Trying to update the plugin to 1.15 but marven and intelji are broke?

### ISSUE THREAD

**Issue by pluttotv** [JitseB/NPCLib#51]
for some reason beside 1.14 which i did manage to update and download...
rest of marven are broke even tho i checked on the site and updated marven according
<dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.X.X.X-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency> 

the change was needed is on line:
<artifactId>spigot-api</artifactId>

using https://hub.spigotmc.org/nexus/#view-repositories;snapshots~browseindex

i cant believe i lost 1-2 hours trying to stackoverflow it and yet cant sit and try to update and implement the actual code for 1.15.2 lol

**Comment by JitseB** [comment]
I have been very busy with my degree, luckily @MrMicky-FR created a PR (#52) and added the necessary code for 1.15.

I'll soon be posting a compiled JAR file on both the repo and SpigotMC.

Sorry for the long wait!
