### ISSUE TITLE
2.4 on spigot 1.15.2

### ISSUE THREAD

**Issue by pluttotv** [JitseB/NPCLib#53]
**Describe the bug**
the holograms are broke,
they change the item meta injection from what i read.

**NPCLib usage option**
last version available 

**NPCLib JAR name**
npclib-plugin-2.4-SNAPSHOT

**Server version**
103 paper , 1.15.2

**To Reproduce**
u see the armor stand above the npc

**Expected behavior**
like before it shows hologram with text and not the armor stand.

**Screenshots**
https://imgur.com/a/S74Oo4w

**Additional context**
as i said from what i read:
https://www.spigotmc.org/threads/holograms-break-on-1-15.408675/
https://www.spigotmc.org/threads/entityarmorstand-doesnt-work.417113/

hope its help

**Comment by Jocke155** [comment]
Can confirm that this issue is happening to me too.

**Comment by JitseB** [comment]
I have fixed the issue you're having (finally). I'll release a new version of NPCLib within a few days.

**Comment by JitseB** [comment]
Enjoy! https://github.com/JitseB/NPCLib/releases/tag/2.4.1-SNAPSHOT
