### ISSUE TITLE
NPCInteractEvent is fired twice

### ISSUE THREAD

**Issue by Jocke155** [JitseB/NPCLib#54]
**Describe the bug**
NPCInteractEvent is fired twice. (One time per hand) but NPCInteractEvent does not offer the EquipmentSlot to determine the hand of the interaction.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/EquipmentSlot.html

**NPCLib usage option**
https://github.com/JitseB/NPCLib#2

**NPCLib JAR name**
npclib-plugin-2.4-SNAPSHOT

**Server version**
CraftBukkit version git-Spigot-8faa8b4-fba9f48 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**To Reproduce**
Listen to NPCInteractEvent, and print something in the console. It will print it twice.

**Expected behavior**
EquipmentSlot to be added to determine the hand of the interaction.

**Comment by JitseB** [comment]
NPCLib already offers support for this. The `ClickType` of the event gives you information on whether it's a right/left click. You may filter your actions accordingly. After the event is triggered, the is a one tick delay before the next event can be fired by the player.

**Comment by Jocke155** [comment]
Yes I already filter on right-click. But in 1.15.2 it seems to fire twice on right-click, one time for OFF_HAND and one time for HAND, which required me to implement my own cooldown.

**Comment by kingOf0** [comment]
> Yes I already filter on right-click. But in 1.15.2 it seems to fire twice on right-click, one time for OFF_HAND and one time for HAND, which required me to implement my own cooldown.

Still occurs. (2.11.1)
