### ISSUE TITLE
ViaVersion incompatibility

### ISSUE THREAD

**Issue by CleusGamer201** [JitseB/NPCLib#58]
**Describe the bug**
When you try to join to a spigot server 1.8.8 using ViaVersion and minecraft client 1.14.4 you get kicked with the exception: **ArrayOutOfBoundsException 6**, im using the last version of ViaVersion.

**NPCLib usage option**
1

**NPCLib JAR name**
Lastest jar

**Server version**
This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Screenshots**
**Console log when i try to join and viaversion kicks me**

[14:26:17 INFO]: UUID of player CleusGamer201 is bdb39cc3-7782-3a37-9f8f-20ee8de60fa0
[14:26:18 WARN]: [ViaVersion] Ignoring plugin channel in outgoing REGISTER: WECUI
[14:26:18 INFO]: CleusGamer201[/***.***.***.***:19668] logged in with entity id 16 at ([world]-1240.7532660643817, 17.0, -857.759500022689)
[14:26:23 INFO]: CleusGamer201 lost connection: Disconnected
[14:26:23 WARN]: handleDisconnection() called twice
[14:26:23 INFO]: CleusGamer201 left the game.

**Comment by BGHDDevelopment** [comment]
For your usage do you mean [Example1](https://github.com/JitseB/NPCLib/blob/master/examples/example-1.java)?

If not can you provide your code for NPCLib. Also is there any other errors on startup and are you able to connect on other versions?

**Comment by CleusGamer201** [comment]
Let's see, I have used this for a long time but it happens that now when I create an npc on a spigot 1.8.8 server with viaversion I can enter with minecraft 1.8.8 without problems but when I use another version like minecraft 1.14 to enter a spigot 1.8.8 server with viaversion, I am kicked with the exception: ArrayOutOfBounds 6, the same thing happens if I enter with 1.15 but if I eliminate the created npcs I can enter without being kicked with 1.14 and with 1.15.

I have no startup errors or anything like that works fine except when I use viaversion to join from a newer version to the server version. Still does not drop errors on the console

**Comment by BGHDDevelopment** [comment]
@CleusGamer201 Can you provide your NPC code, please.

**Comment by CleusGamer201** [comment]
**I create the npcs for my game with.**
`List<String> holoText = config.getStringList("HologramLines");
Skin skin = MineSkinFetcher.fetchSkinFromIdSync(307358);
for(String key : config.getConfigurationSection("NPCs").getKeys(false)) {
	String loc = config.getString("NPCs." + key);
	Location npcloc = locFromString(loc).add(0.5, 0.0, 0.5);
	NPC npc = npclib.createNPC(holoText);
	npc.setSkin(skin);
	npc.setLocation(npcloc);
	npc.create();
	players.forEach(npc::show);
	npcscontroller.addNPC(npc);
}`

**When a player join to my game i show the npcs.**
for (NPC npc : npcscontroller.getAll()) {
         npc.show(p);
}

**I've read that its not necessary to hide the npcs on leave the server, i only hide the npcs if are using multiarena and the player leave from the game**
`for (NPC npc : npcsc.getAll()) {
	if(npc.isShown(p)) {
		npc.hide(p);
	}
}`

Sorry for my bad english, i speak spanish.

**Comment by BGHDDevelopment** [comment]
Coming back to this I am experiencing the same issue.

Server base is 1.8 (with viaversion), when any player joins with 1.9+ they get kicked for - https://photos.bghddevelopment.com/u/17.55.52-06.04.20.png
ArrayIndexOutOfBoundsException: 6

Using Java 8 in relation to the other issue opened with this.

**Comment by CleusGamer201** [comment]
> Coming back to this I am experiencing the same issue.
> 
> Server base is 1.8 (with viaversion), when any player joins with 1.9+ they get kicked for - https://photos.bghddevelopment.com/u/17.55.52-06.04.20.png
> ArrayIndexOutOfBoundsException: 6
> 
> Using Java 8 in relation to the other issue opened with this.

Yes, yes, Exactly they are the error.

**Comment by JitseB** [comment]
I have little free time on hand, I'll try to fix other issues regarding the library tonight. However, thanks to @MrMicky-FR this issue has been resolved. I'll soon post an update that includes this fix.

**Comment by JitseB** [comment]
https://github.com/JitseB/NPCLib/releases/tag/2.4.2-SNAPSHOT
