### ISSUE TITLE
Edit NPC Text (Question)

### ISSUE THREAD

**Issue by thisisfel1x** [JitseB/NPCLib#60]
Hey,

so a few days ago, I asked myself if its possible to edit a NPCs text even if he's already created and displayed to a player. 
I didn't found any way to to that, so I hope to get some help on GitHub :)

fel1x

**Comment by JitseB** [comment]
Hi, you can use the update method in NPCLib.
https://github.com/JitseB/NPCLib/blob/master/api/src/main/java/net/jitse/npclib/api/NPC.java#L122
Cheers!

**Comment by thisisfel1x** [comment]
I'm a bit confused, because I do it exactly this way.

`data.getSw2NPC().setText("...");`

**Comment by JitseB** [comment]
Are you getting an exception? Also this parameter of this method is a String list, not a String array. You might be looking for `Arrays.asList(String[] text...)`.

**Comment by thisisfel1x** [comment]
Sorry, it was just an example.
Thats how I want to update the text:

`data.getSw1NPC().setText(Arrays.asList(new String[]{" Yes", "Updated text :)"}));`
