### ISSUE TITLE
Updating NPC's

### ISSUE THREAD

**Issue by Acixsi** [JitseB/NPCLib#63]
Hi there,

I just created NPC's for my server and stored them inside a config (NPC ID, Location, skinvalue, skinsignature etc..) but I would like to know if it's possible to update the text above the head of the NPC (this is my playercount for BungeeCord), and if it's possible, how can I do that? Same for; how to destroy them? Cause in events I can get the NPC ID en check if it's in my config but in methods i can't.

I hope u can help me.

Kind regards,
Franck

**Comment by andrei923** [comment]
NPC#setText

**Comment by Acixsi** [comment]
But what if I have multiple NPC's? Isn't it that when I setText every npc changes into the same name? I think I need to define a NPC right?

**Comment by JitseB** [comment]
Hallo Frank,


You don’t need to save the NPC ID in a config file. You can just iterate over the input settings in the config, then create all NPC accordingly and put them in your own manager class. Then, when you want to see which NPC is clicked or which NPC should have its text updated, you can just refer to your manager class. That way your code becomes dynamic! 😛

Best of luck with your plugin!

**Comment by Acixsi** [comment]
Hi Jitse,

Do you maybe have an example? I don't really understand what you mean... I'm sorry...

**Comment by JitseB** [comment]
I’ve tried to put it into pseudo code as best as I can;
```
class manager {
List<NPC> npcs;

void register(npc) {
// Register NPC in list.
}

// then on startup:
for entry in config:
// Entry in configfile contains all information for the NPC.
NPC npc = npclib.createNPC(entry)
npc.show(players)
// Then save the NPC’s information in the manager.
manager.register(npc)

// Then on the NPCInteractEvent
void interact {
NPC npc = manager.getNPCfromID(id)
// do stuff
}
```

Don’t forget to remove NPCs from the `npcs` list if you’re not using them anymore.
You could also create a wrapper class for your NPCs to “add in” the text that it should loop through. Kind of like so:
```
class CoolNPC {
NPC npc

CoolNPC(NPC npc, List<List<String>> texts) {
this.npc = npc
}
```

Then it’s just a matter of looping through the texts and applying them to NPC object.

I hope this helps.

Best of luck!

**Comment by JitseB** [comment]
Closing issue as I think it’s resolved. You may reopen this ticket any time!
Have a good day. :)
