### ISSUE TITLE
LabyMod Support

### ISSUE THREAD

**Issue by rexlManu** [JitseB/NPCLib#65]
Hello,

i want to suggest to add labymod support. I mean with labymod support the emote api.
For this feature you need the ability to change the uuid. (https://docs.labymod.net/pages/server/emote_api/) out of the docs the uuid needs to be " emotes can only be forced for players that have the second half of their UUID entirely being 0 (-> 64 least significant bits are 0, or the second long value equals 0)". You could add also the method for playing a emote.

I already done this on a fork (https://github.com/rexlManu/NPCLib/blob/master/api/src/main/java/net/jitse/npclib/internal/NPCBase.java#L58) but i just rushed it into the lib and i think its not really nice placed in the class, so i think its better when u add it to the lib in your way, i hope you know what i mean.

**Comment by JitseB** [comment]
I’ll look into this tonight. Thanks for the request, I think it’ll be a nice addition to NPCLib.

**Comment by JitseB** [comment]
I don’t think you placed it in a weird place. I’ll add some documentation and copy over your code to the master branch.
Later today I’ll post an update to NPCLib containing the necessary code.

**Comment by JitseB** [comment]
I have posted a release with the support here: https://github.com/JitseB/NPCLib/releases/tag/2.5-SNAPSHOT

If you happen to find any issues, feel free to reopen this ticket. For now I'm closing it.
Have a good day!
