### ISSUE TITLE
SlimeWorldManager support

### ISSUE THREAD

**Issue by rexlManu** [JitseB/NPCLib#66]
Hello,

i want to suggest to add slimeworldmanager support.
I already figured out what the problem is why armorstands cant be spawned. Thats because of the
worldserver class, you just need to get the superclass of it.

**Comment by JitseB** [comment]
The holographic part of NPCLib should already be looking for the superclass since 2.4.2, which I released last night. This seems to be a similar issue to #59.
Have you tried the latest version yet?

**Comment by rexlManu** [comment]
I had the version 2.4.1, yea its fixed, good work!
