### ISSUE TITLE
NPCs don't show after respawn

### ISSUE THREAD

**Issue by matthiastorm** [JitseB/NPCLib#69]
**Describe the bug**
The NPC's do not show after a respawn.

**NPCLib usage option**
2

**NPCLib JAR name**
npclib-plugin-2.5-SNAPSHOT.jar

**Server version**
Paper version git-Paper-172 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**To Reproduce**
- at respawn event, i check if the npc is shown to the player. 
- it says, that npc is shown to the player every time.
- after i fly out of the auto hide range, and fly back in again, the npcs show.

**Expected behavior**
I expected to see the npcs

**Comment by JitseB** [comment]
I totally forgot to handle the NPC at the PlayerRespawnEvent. Thanks for opening this issue!
I’ll push a fix tomorrow. I’ve got exams today.

**Comment by JitseB** [comment]
Fixed in 2.5.1-SNAPSHOT. You can download it here: https://github.com/JitseB/NPCLib/releases/tag/2.5.1-SNAPSHOT
(I've also deployed it to the Maven repo already).
Have a good day!

**Comment by matthiastorm** [comment]
Thanks for fixing this,
I really appreciate your hard work for this nice API!
