### ISSUE TITLE
NPCLib Failed to initiate. Your server's version (v1_15_R1) is not supported

### ISSUE THREAD

**Issue by FrederikHeinrich** [JitseB/NPCLib#72]
**Describe the bug**
Server Version is not Supportet?

**NPCLib usage option**
3

**NPCLib JAR name**

**Server version**
git-Paper-185 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**To Reproduce**
`@Override
	public void onEnable() {
		NPCLib npclib = new NPCLib(this);
	}`

**Expected behavior**
Failed to initiate

**Screenshots**
none

**Additional context**
none

**Comment by JitseB** [comment]
Hi, thanks for opening this issue ticket!

NPCLib should support 1.15 R1. If you're using option 3, have you read the footnote?
_If you do not want to have NPCLib in your plugins folder, you need to use the npclib-plugin artifact and shade it accordingly._

**Comment by FrederikHeinrich** [comment]
ohhh... thx i´m stupid. x_x
