### ISSUE TITLE
My NPC disappers!

### ISSUE THREAD

**Issue by GDev812** [JitseB/NPCLib#73]
**Describe the bug**
My NPC and hologram disappear after a while.

**NPCLib usage option**
Code: https://hasteb.in/afosijas.java

**NPCLib JAR name**
E.g. npclib-plugin-2.5.1-SNAPSHOT.jar

**Server version**
spigot 1.8.8

**Expected behavior**
The NPC is there at the beginning, after a short time it is gone. That doesn't always happen, but more often than the NPC stays. The time after the NPC disappears is different

**Screenshots**
No. Can't take a screenshot because the NPC disappears after a while

**Additional context**
The NPC only disappears sometimes, but when it disappears it is only back when I am far away from it and come back

**Comment by JitseB** [comment]
Yes, I know. Hopefully it’ll be fixed after today.
Closed. Duplicated of #70.
